substitutions:
####### change CHANGEME
  room: CHANGEME #(ROOM NAME)
  climate: ‘CHANGEME’ ##### Termostato (climate)
  switch_acs: ‘CHANGEME’  ##### Interruptor de la boba de recirculación ACS
  ip: CHANGEME
  #tft_url: http://192.168.1.100:8123/local/nspanel_mikasa.tft
  tft_url: https://raw.githubusercontent.com/ppernias/thingernet_NSPthermostat/master/nspanel_mikasa.tft
  v_offset: '0.0' #offset value for calibrate ntc
  ha_hotwater_charge: ‘CHANGEME’ ##### interruptor (o boolean) que enciende agua caliente
  t_acs: ‘CHANGEME’ ### sensor temperatura retorno ACS
  t_outdoor: ‘CHANGEME’
  default_background: '0'
  web_password: !secret tasmota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  ota_password: !secret ota_password 
####### change me end #########

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/ppernias/thingernet_thermostate
    ref: master
    files: [nspanel_mikasa.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####