substitutions:
####### change me start #########
  device_name: CHANGEME
  room: CHANGEME ####roomname
  climate: 'climate.CHANGEME’ ##### ASSOCIATED HA CLIMATE
  switch_heater: ‘CHANGEME’ ##### HEATER SWITCH (IN HA CLIMATE)
  switch_acs: ‘CHANGEME’  ##### SWITCH FOR HOT WATER RECIRCULATION
  ip: CHANGEME
  #tft_url: http://YOURHAIP:8123/local/nspanel_mikasa.tft
  tft_url: https://raw.githubusercontent.com/ppernias/thingernet_NSPthermostat/master/nspanel_mikasa.tft
  v_offset: ‘0.0’ ##### DEFAULT OFFSET VALUE
  ha_hotwater_charge: ‘CHANGEME’ ##### BOOLEAN SWITCH TO ASK FOR HOT WATER
  t_sr: ‘CHANGEME’  #### TEMPERATURE OF HEATING SYSTEM IMPULSION
  t_acs: ‘CHANGEME’ ### HOT WATER RETURN TEMPERATURE
  t_outdoor: ‘CHANGEME’ ### OUTDORR TEMPERATURE SENSOR
  web_password: !secret YOURPASSWORDFORWEBSERVER
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  ota_password: !secret ota_password 
####### change me end #########

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/ppernias/thingernet_NSPthermostat
    ref: master
    files: [nspanel_mikasa.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
